version: '3'
services:
  phi-mysql:
      image: mysql:latest
      container_name: "phi-mysql"
      environment:
        MYSQL_DATABASE: website
        MYSQL_USER: admin
        MYSQL_PASSWORD: q7W#t&d)CYxt8dK
        MYSQL_ROOT_PASSWORD: q7W#t&d)CYxt8dK
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      restart: always
      ports:
        - 3306:3306
      networks:
        - phi-network

networks:
  phi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.4.0/26
          gateway: 192.168.4.1