version: '2'
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017

networks:
  phi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.4.0/26
          gateway: 192.168.4.1